#!/bin/bash
# 三工具搭配一键部署脚本
#  usage: bash deploy-kb-stack.sh [vault_path]

set -e
VAULT_PATH="${1:-$HOME/obsidian-vault}"
KB_PATH="$HOME/kb-swarmvault"
CODEBASE_CACHE="$HOME/.cache/codebase-memory-mcp"

echo "=== 1. 检查已安装工具 ==="
command -v swarmvault >/dev/null || { echo "❌ swarmvault 未安装"; echo "运行：npm install -g @swarmvaultai/cli"; exit 1; }
command -v codebase-memory-mcp >/dev/null || { echo "❌ codebase-memory-mcp 未安装"; echo "运行：curl -fsSL https://raw.githubusercontent.com/DeusData/codebase-memory-mcp/main/install.sh | bash"; exit 1; }
echo "✅ swarmvault: $(swarmvault --version)"
echo "✅ codebase-memory-mcp: $(codebase-memory-mcp --version)"

echo ""
echo "=== 2. 初始化目录结构 ==="
mkdir -p "$VAULT_PATH"/{00-Inbox,99-Archive,SwarmVault,Templates}
mkdir -p "$KB_PATH"/{raw,wiki,state,outputs}
mkdir -p "$CODEBASE_CACHE"

# 创建 symlink: SwarmVault → Obsidian
if [ ! -L "$VAULT_PATH/SwarmVault" ]; then
  rm -rf "$VAULT_PATH/SwarmVault"
  ln -s "$KB_PATH/wiki" "$VAULT_PATH/SwarmVault"
  echo "✅ 创建 symlink: $VAULT_PATH/SwarmVault -> $KB_PATH/wiki"
else
  echo "✅ symlink 已存在"
fi

echo ""
echo "=== 3. 初始化 SwarmVault ==="
cd "$KB_PATH"
if [ ! -f "swarmvault.config.json" ]; then
  swarmvault init .
  echo "✅ SwarmVault 初始化完成 @ $KB_PATH"
else
  echo "✅ SwarmVault 已初始化"
fi

echo ""
echo "=== 4. 配置 codebase-memory-mcp ==="
# 索引 Hermes 技能目录作为示例
codebase-memory-mcp cli index_repository "{\"repo_path\":\"$HOME/.hermes/skills\",\"project_name\":\"hermes-skills\"}" 2>&1 | tail -3
echo "✅ codebase-memory-mcp 已配置 (示例：hermes-skills)"

echo ""
echo "=== 5. 创建 Obsidian 配置提示 ==="
cat > "$VAULT_PATH/README-KB-SETUP.md" << 'OBSIDIAN_TIPS'
# Obsidian 知识库配置提示

## 目录说明
- **00-Inbox/** — 快速笔记暂存区 (SwarmVault 会定期处理)
- **SwarmVault/** — symlink 到 SwarmVault wiki，自动同步的技术文档
- **99-Archive/** — 手动归档的旧笔记
- **Templates/** — 笔记模板

## 推荐 Obsidian 插件
1. **Dataview** — 查询笔记元数据
2. **Templater** — 自动填充笔记模板
3. **QuickAdd** — 快速捕获想法到 Inbox
4. **Git** — 版本控制 (配合 swarmvault watch --git-hooks)

## 与 SwarmVault 协作流程
1. 人类在 `00-Inbox/` 写快速笔记
2. 运行 `swarmvault scan 00-Inbox/ --output wiki/` 处理
3. 在 `SwarmVault/` 目录查看生成的文档
4. 手动移动到对应分类或归档

## 与 codebase-memory-mcp 协作
- 代码架构图导出：`codebase-memory-mcp cli get_architecture --project=xxx --output=markdown`
- 输出保存到 `raw/code-architecture/`
- SwarmVault 会自动 ingestion 并生成 wiki 页面
OBSIDIAN_TIPS

echo "✅ 已创建 Obsidian 配置提示：$VAULT_PATH/README-KB-SETUP.md"

echo ""
echo "=== 6. 创建定时任务脚本 ==="
cat > "$HOME/.hermes/scripts/kb-sync.sh" << 'CRON_SCRIPT'
#!/bin/bash
# 每日凌晨 2 点同步知识库
# crontab -e 添加：0 2 * * * bash ~/.hermes/scripts/kb-sync.sh

set -e
cd "$HOME/kb-swarmvault"

# 1. 扫描新素材
if [ -d "$HOME/downloads/papers" ]; then
  swarmvault scan "$HOME/downloads/papers" --output wiki/ 2>&1 | tail -5
fi

# 2. 处理 Obsidian Inbox
if [ "$(ls -A "$HOME/obsidian-vault/00-Inbox" 2>/dev/null)" ]; then
  swarmvault scan "$HOME/obsidian-vault/00-Inbox" --output wiki/ 2>&1 | tail -5
fi

# 3. 编译图谱
swarmvault compile --auto-approve 2>&1 | tail -5

# 4. 检测矛盾
swarmvault lint --conflicts 2>&1 | tail -5 || echo "⚠️ 发现矛盾，需人工审阅"
CRON_SCRIPT

chmod +x "$HOME/.hermes/scripts/kb-sync.sh"
echo "✅ 已创建定时任务脚本：$HOME/.hermes/scripts/kb-sync.sh"

echo ""
echo "=== 部署完成 ==="
echo ""
echo "下一步操作:"
echo "1. 打开 Obsidian，选择 $VAULT_PATH 作为 vault"
echo "2. 安装推荐插件 (Dataview, Templater, QuickAdd, Git)"
echo "3. 在 Obsidian 中阅读 $VAULT_PATH/README-KB-SETUP.md"
echo "4. 测试 SwarmVault: cd $KB_PATH && swarmvault next"
echo "5. 测试 codebase-memory-mcp: codebase-memory-mcp cli list_projects"
echo "6. 可选：添加 cron 任务 (0 2 * * * bash $HOME/.hermes/scripts/kb-sync.sh)"
echo ""
echo "Generated by Hermes"